# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#F4A261"        # narancssárga – ikonok, kiemelések
body_color = "#1B3B5F"           # világosabb, de mélykék háttér
text_color = "#FDFDFD"           # fő szöveg – világos, de nem vakító
text_dark = "#FFFFFF"            # erősen világos szöveg
text_light = "#E9C46A"           # világos narancs – halványabb szöveg, árnyalat
border_color = "#2D4D70"         # világosabb kékszürke – finom kontúr
black = "#000"
white = "#FFF"
light = "#29476B"                # világosabb háttérszín részelemekhez

# font variables
font_size = "15px"
font_scale = "1.3"

# Modern, tech hangulatú, de elegáns betűtípusok
font_primary = "Rubik:wght@400;500;700"
font_primary_type = "sans-serif"

font_secondary = "Merriweather Sans:wght@400;700"
font_secondary_type = "sans-serif"

font_icon = "Font Awesome 6 Free"



############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
# [[params.plugins.js]]
# link = "plugins/glightbox.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
# [[params.plugins.js]]
# link = "plugins/lazy-loader.js"
# [[params.plugins.js]]
# link = "https://cpwebassets.codepen.io/assets/embed/ei.js"
# attributes = "async"
