############# English navigation ##############

# main menu
[[main]]
name = "Kezdőlap"
url = ""
weight = 1

[[main]]
name = "Rólam"
url = "about/"
weight = 2

[[main]]
name = "Kapcsolat"
url = "contact/"
weight = 3

[[main]]
identifier = "galeria"
name = "Galéria"
url = "/galeria/"
weight = 4

[[main]]
name = "Oldalak"
url = "#"
weight = 5
hasChildren = true

  [[main]]
  parent = "Oldalak"
  name = "Címkék"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Oldalak"
  name = "Kategóriák"
  url = "categories/"
  weight = 2

# footer menu
[[footer]]
name = "Kezdőlap"
url = "/"
weight = 1

[[footer]]
name = "Rólam"
url = "about/"
weight = 2

[[footer]]
name = "Kapcsolat"
url = "contact/"
weight = 3

[[footer]]
name = "Adatvédelmi irányelvek"
url = "privacy-policy/"
weight = 4

