#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "150x"
# logo text will only show when logo is missing.
logo_text = "Mark"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Hungary, Szeged"
email = "hello@vargamark.site"
# contact form action
contact_form_action = "https://formspree.io/f/xjkyawyj" # contact form works with 
# search
search = true

# Posts related Titles & Contents
categories_title = "Blogkategóriák"
posts_title = "Kiemelt"
featured_post_title = "Kiemelt bejegyzés"
recent_post_title = "Legutóbbi bejegyzés"
featured_post_button = "Kiemelt"
recent_post_button = "Legutóbbi"
read_more_button = "Tovább olvasom"
previous_button = "Előző"
next_button = "Következő"
related_posts = "Kapcsolódó bejegyzések"
showing_posts = "Megjelenített bejegyzés innen"
no_categories_found = "Nem található kategória"
no_tags_found = "Nem található címke"

mainSections = ["blog"]
# about widget content
about_widget_content = "Üdvözöllek a blogomon! Itt megosztom a gondolataimat, tapasztalataimat és hasznos információkat különböző témákban. Kövess, hogy ne maradj le az új bejegyzésekről!"
# footer content
footer_content = "Köszönöm, hogy ellátogattál a blogomra! Remélem, találsz számodra érdekes és értékes tartalmakat. Ha kérdésed van, bátran írj nekem!"
# custom script on header, example: custom_script= "<script>console.log(\"Üdvözöllek a blogomon!\")</script>" 
custom_script= ""
# copyright
theme_copyright = true
copyright = "Copyright © 2025 Varga Márk. Minden jog fenntartva."

# 404
error_404_text = "Hoppá! Eltévedtél az internet sötét zugában... 😱"
error_404_button = "Vigyél vissza a biztonságba!"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Üdvözöllek **!**"
title_small = "Varga Márk blogján"
image = "images/banner.png"
background_image = "/images/banner-bg-shape.svg"
content = "Gondolatok, történetek és hasznos tartalmak egy helyen. Nézz körül és fedezd fel a legújabb bejegyzéseimet!"
button_label = "Tudj meg többet rólam"
button_link = "about/"

# Advertise
[advertisement]
image = "images/promotion.png"
link = "#"

# cookies
[cookies]
enable = true
expire_days = 2
content = "Ez a weboldal sütiket használ. A böngészés folytatásával elfogadod azok használatát."
button = "Elfogadom"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = true
newsletter_title = "Hírlevél"
newsletter_invitation = "Iratkozz fel, és értesülj elsőként a legújabb bejegyzéseimről!"
newsletter_placeholder = "Írd be az e-mail címed és nyomj Entert"
newsletter_reminder_a = "Feliratkozásoddal elfogadod az"
newsletter_reminder_b = "Adatvédelmi szabályzatot"
newsletter_button = "Feliratkozás"
# mailchimp subsciption
mailchimp_form_action = "https://site.us12.list-manage.com/subscribe/post?u=3dd27dc3d0aaf3bde4088eac6&amp;id=6c3dd5cffd&amp;f_id=001584e0f0" # replace this url with yours
mailchimp_form_name = "b_3dd27dc3d0aaf3bde4088eac6_6c3dd5cffd" # replace this code with yours


############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/mark.varga.507/"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.instagram.com/varga.mark.00?igsh=eGFpYjJsNDVodzM5"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/in/m%C3%A1rk-varga-428349255/"
